### ISSUE TITLE
Desenho Não Espelhado

### ISSUE THREAD

**Issue by gilviegas** [davidgermanorodrigues/Trabalho2_Grupo4#3]
A imagem obtida da câmara não está espelhada, por consequente quando movimentamos um objecto para a direita estamos a desenhar para a esquerda, vice-versa.

**Comment by davidgermanorodrigues** [comment]
Coloca esta linha de código seguinte, logo a seguir à linha 63.
-> image = cv2.flip(image, 1)

Experimenta assim, deve funcionar.
